env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
plugins:
  - '@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
rules:
  indent:
    - 'error'
    - 2
